<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NCoreUtils.AspNetCore.OAuth2</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <!-- <NoWarn>IL2104</NoWarn> -->
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants Condition=" '$(NoMetrics)' != 'true' ">$(DefineConstants);ENABLE_GOOGLE_K8S_METRICS</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition=" '$(NoMetrics)' != 'true' ">
    <PackageReference Include="NCoreUtils.Extensions.Google.Cloud.Monitoring.ServiceAccount" Version="8.1.6.4-beta03" />
    <Compile Include="..\Shared\GoogleMetrics\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.OAuth2.LoginProvider.Client\NCoreUtils.OAuth2.LoginProvider.Client.csproj" />
    <ProjectReference Include="..\NCoreUtils.OAuth2.TokenService\NCoreUtils.OAuth2.TokenService.csproj" />
    <ProjectReference Include="..\NCoreUtils.OAuth2.TokenService.AspNetCore\NCoreUtils.OAuth2.TokenService.AspNetCore.csproj" />
    <ProjectReference Include="..\NCoreUtils.OAuth2.TokenService.Encryption.Aes\NCoreUtils.OAuth2.TokenService.Encryption.Aes.csproj" />
    <ProjectReference Include="..\NCoreUtils.OAuth2.TokenService.TokenRepositories.GoogleCloudFirestore\NCoreUtils.OAuth2.TokenService.TokenRepositories.GoogleCloudFirestore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.AspNetCore.ForwardedHeaders" Version="8.0.0" />
    <PackageReference Include="NCoreUtils.AspNetCore.Logging" Version="8.1.0-rc00" />
    <PackageReference Include="NCoreUtils.Logging.Google.Fluentd" Version="8.1.0-rc00" />
  </ItemGroup>
</Project>
