<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>NCoreUtils.OAuth2</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.Data.Abstractions" Version="$(NCoreUtilsDataVersion)" />
  </ItemGroup>
</Project>
