<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>NCoreUtils.OAuth2</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.OAuth2.TokenService.Internal.Abstractions\NCoreUtils.OAuth2.TokenService.Internal.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Core" Version="$(GrpcVersion)" />
    <PackageReference Include="NCoreUtils.Data.Generator" Version="8.0.0-rc04" />
    <PackageReference Include="NCoreUtils.Data.Google.Cloud.Firestore" Version="8.0.0-rc04" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <Compile Include="..\Shared\Trimming\*.cs" />
    <Compile Include="..\Shared\Nullable\*.cs" />
  </ItemGroup>
</Project>
