<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>NCoreUtils.OAuth2</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.Data.EntityFrameworkCore" Version="8.0.1-rc04" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.1' ">
    <Compile Remove="CodeAnalysis\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.OAuth2.TokenService.Internal.Abstractions\NCoreUtils.OAuth2.TokenService.Internal.Abstractions.csproj" />
  </ItemGroup>
</Project>
