<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;netstandard2.1;net48</TargetFrameworks>
    <RootNamespace>NCoreUtils.OAuth2</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <NoWarn>CS8601;CS8618;CS8602;CS8604</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.OAuth2.Abstractions\NCoreUtils.OAuth2.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.1' And '$(TargetFramework)' != 'net48' ">
    <Compile Remove="LoginIdentity.Compat.cs" />
  </ItemGroup>
</Project>
